### ISSUE TITLE
Doesn't work with timestamped snaphots

### ISSUE THREAD

**Issue by softdays** [phreakadelle/maven-artifact-choicelistprovider-plugin#10]
We are using Maven 3 with Nexus 2 repository, so all our snapshots are stored using timestamp.
When we try to use the artefact-choice-listprovider plugin to retrieve a snapshot, the plugin ignores the  timestamp part of the artifact name and it causes an http 404 error on wget download.
Could you provide a way to list snapshots with their timestamp suffix?

**Comment by phreakadelle** [comment]
Hey @softdays . Yeah, this is more or less a feature and not a bug ;-) You're right that the plugin only returns the latest snapshot of the artifact and not all of them. 

From my point of view it doesnt make sense to browse through the history of snapshots. As a consumer you would like to have the most recent one.

In our projects we have changed the way working with Git and Maven slightly. Thus the feature-branch name gets part of the Maven-Version. Thus our artifacts are easily to identify and you could still rely on snapshots.

**Comment by softdays** [comment]
Sorry for the delay. From my point of view, the plugin doesn't work as expected with snapshots or there is a incompatibility with Nexus. It does't return the last snapshot, as I said we got an http error (404).

**Comment by phreakadelle** [comment]
So i havent faced any issues with the Plugin and using Snapshots from Nexus. With the plugin we always retrieve the latest Snapshot version. This is what i expect.

**Comment by softdays** [comment]
This issue should not be closed. The plugin doesn't work as expected as it throws 404 http error when we try to get snapshot.

**Comment by softdays** [comment]
The plugin works only when getting release artifact reference

**Comment by phreakadelle** [comment]
Show me!

For us it looks like this:

![image](https://user-images.githubusercontent.com/645665/50334444-9b023080-0508-11e9-9c26-f71d40739acb.png)

**Comment by softdays** [comment]
Ok what do you do with the retrieved snapshot url?
My usage is the following:
1. I use your plugin to get a snapshot url as a job parameter 
![image](https://user-images.githubusercontent.com/948293/50348719-ea148980-0539-11e9-8df7-0dcfe6864148.png)
2. Then I use the Http Request Builder to download the snapshot
![image](https://user-images.githubusercontent.com/948293/50348819-2f38bb80-053a-11e9-9ea7-0dcce0fd8950.png)
3. When I execute the job I get an http 404 error:
![image](https://user-images.githubusercontent.com/948293/50348968-98b8ca00-053a-11e9-85bb-40e9e542bcce.png)

**Comment by phreakadelle** [comment]
@softdays have you tried to go to "Jenkins" -> "Manage" and tick the Checkbox to use the RESTful API of Nexus? Only this one supports the usage of Snapshots. Please try if this is sufficient for you.

**Comment by softdays** [comment]
@phreakadelle many thanks for your help. The plugin works now as expected with snapshots. Maybe it could help to add this tip in the doc...

Anyway for anyone interested: `Manage Jenkins > Configure System > Extensible Choice: Maven-Artifact-ChoicelistProvider Plugin > Use RESTful Nexus API > true`

![image](https://user-images.githubusercontent.com/948293/50377143-3fbf6380-0618-11e9-8495-bdd9857785d7.png)

**Comment by phreakadelle** [comment]
Ok. Great. Thanks!
