### ISSUE TITLE
For Artifactory it doesn't give the download URI

### ISSUE THREAD

**Issue by melhossarySG** [phreakadelle/maven-artifact-choicelistprovider-plugin#11]
for Artifactory, this plugin provides the artifact URI and NOT the download URI.
if you do a wget on the artifact URI, it will dowload the artifact JSON file and not the artifact itself!

**Comment by phreakadelle** [comment]
As a first Workaround you can install "json" command line tool:

```
stephan@swpws0401:~$ which json
json --version
json 9.0.6
written by Trent Mick
https://github.com/trentm/json
```

The you are able to download the file via "wget"
`wget https://repo.jenkins-ci.org/api/storage/releases/org/jenkins-ci/plugins/ant-in-workspace/1.1.0/ant-in-workspace-1.1.0-javadoc.jar`

And in a second step you can just do 
```
cat ant-in-workspace-1.1.0-javadoc.jar | json uri
https://repo.jenkins-ci.org/api/storage/releases/org/jenkins-ci/plugins/ant-in-workspace/1.1.0/ant-in-workspace-1.1.0-javadoc.jar
```
