### ISSUE TITLE
Random artifacts order when retrieving them from nexus3

### ISSUE THREAD

**Issue by abdelinho-testdaf** [phreakadelle/maven-artifact-choicelistprovider-plugin#13]
when retrieving artifacts from nexu3 is the order of artifacts random, that's in case of a big repository not helpfull, in our company we would like to retrieve the LAST deployed artifacts (as example 50), we would be  grateful, we are blocked in our jenkins and the developers can't choose the last artifacts they had deployed, thank you a lot

**Comment by phreakadelle** [comment]
I think there is no way to determine the sort order of results in the Sonatype Nexus 3 API. Haven't found anything so far.

* https://help.sonatype.com/repomanager3/rest-and-integration-api/search-api
* https://help.sonatype.com/repomanager3/rest-and-integration-api/assets-api

I think the only way to get all artifacts is make use of this "continuationToken" to get the next results. This will end up in multiple repository calls. And this is quiet a bit of effort to imlpement it.

**Comment by phreakadelle** [comment]
@Hirashiki:

* https://github.com/phreakadelle/maven-artifact-choicelistprovider-plugin/issues/14

**Comment by phreakadelle** [comment]
I am working on that... 
https://github.com/phreakadelle/maven-artifact-choicelistprovider-plugin/commit/655bed593f7cb8a31ef49b589db6bd1084bfd346

**Comment by abdelinho-testdaf** [comment]
@phreakadelle 1.3.3 works, on my fork i solved the problem with invoking the same retrieve method recursively, are you going to make a release?

**Comment by abdelinho-testdaf** [comment]
@phreakadelle
