### ISSUE TITLE
Nexus3 Artifact Choice Parameter with ContinuationToken?

### ISSUE THREAD

**Issue by Hirashiki** [phreakadelle/maven-artifact-choicelistprovider-plugin#14]
If nexus3 has more than 50 artifacts in result, it add a "continuationToken" in response, but the plugin is fixed to make only one request.

Its possible to implement in official git? I tested with source code and its possible to implement with little changes in Nexus3RestApiSearchService.

Thanks

**Comment by phreakadelle** [comment]
Hi @Hirashiki and thanks for your Feedback. The problem you are describing is already discussed here: 
* https://github.com/phreakadelle/maven-artifact-choicelistprovider-plugin/issues/13
