### ISSUE TITLE
Nexus 3 repository dont list files

### ISSUE THREAD

**Issue by camillagds** [phreakadelle/maven-artifact-choicelistprovider-plugin#2]
Hello,

I received this message when I configure the plugin and click on LIST FILES NOW:

HTTP Server Error: 404: GET http://<IP_OF_SERVER>:8081/repository/<REPONAME>/service/local/lucene/search?p=zip&a=<ARTIFACT>&g=<GROUP> returned a response status of 404 Not Found

But the format of the url is http://<IP_OF_SERVER>:8081/repository/<REPONAME>/<GROUP>/<ARTIFACT>/1.0.0/<ARTIFACT>-1.0.0.zip

**Comment by phreakadelle** [comment]
Thanks for reporting an issue! I have to setup a nexus 3 and test it by myself. I think i can make it after christmas. Thanks!

**Comment by phreakadelle** [comment]
@camillagds : Is the Lucene Search Service available on your repository? Are you able to call this URL?
http://<YourServerIP>/nexus/service/local/lucene/search

**Comment by phreakadelle** [comment]
@camillagds : Sorry, but there is not RESTful interface for NEXUS3. According to their JIRA it will be implemented in the future: 
* https://issues.sonatype.org/browse/NEXUS-11893

So i'll close this issue as long as Nexus3 is not supporting this feature.
