### ISSUE TITLE
Artifact list shows incorrect order

### ISSUE THREAD

**Issue by WeTheNorth93** [phreakadelle/maven-artifact-choicelistprovider-plugin#24]
The order of the artifacts in a given nexus repo becomes out of order when the number of artifacts gets into double digits (10,11,12 etc)

**Comment by phreakadelle** [comment]
Have you tried to activate the REST API in the options? I think there is a pretty similar issue here...

**Comment by WeTheNorth93** [comment]
I'm using nexus3, is it correct that Restful API is not supported by Nexus 3? i have the option ticked true already, not sure if de-selecting that will make any difference

**Comment by WeTheNorth93** [comment]
@phreakadelle please see the included snapshot of the issue i'm facing. When the release version gets to double digit (10,11,12 etc) the order of the artifact list is not correct. I expected 29.0.10 to be after 29.0.9 ... but it comes after 29.0.1

![image](https://user-images.githubusercontent.com/60986511/80391060-3c2a9500-887b-11ea-832e-4c8bba26413f.png)

**Comment by phreakadelle** [comment]
Yes I know that issue. And therefore you should use the restful interface, as mentioned in #3
