### ISSUE TITLE
Support for Nexus 3.x

### ISSUE THREAD

**Issue by anitakrueger** [phreakadelle/maven-artifact-choicelistprovider-plugin#4]
I'm trying to use the plugin to gather artifact versions from a Nexus 3.2 repo, but unfortunately only get 404s when trying to retrieve the artifact metadata.
I know Nexus 3.x dropped the REST api (stupid in my opinion), so is there a way to just go back to using the maven-metadata.xml and parse that? I've tried the other Choice Providers, but none of them seems to do this.

Any help would be much appreciated.

**Comment by phreakadelle** [comment]
The code for The old approach is still in. Maybe i Can Build a Version where it will be configurable. Will get back to this End of next week

**Comment by anitakrueger** [comment]
Thanks a lot for looking at it! :)

**Comment by phreakadelle** [comment]
I've highlighted that issue some time back this year already in the Sonatype Issue Tracker:
* https://issues.sonatype.org/browse/NEXUS-11893

**Comment by SaschaJohn** [comment]
@anitakrueger I raised a pull request to support Nexus3

**Comment by anitakrueger** [comment]
@SaschaJohn so awesome! Thanks! I've been using their new REST API in other projects and it was about time it came back

**Comment by phreakadelle** [comment]
I've merged the code back and will integrate @SaschaJohn changes on Monday. Then the new version will be available. 
https://github.com/phreakadelle/maven-artifact-choicelistprovider-plugin/tree/feature/nexus-3-restful-api
