### ISSUE TITLE
Missing dash

### ISSUE THREAD

**Issue by Reamer** [phreakadelle/maven-artifact-choicelistprovider-plugin#9]
Hi,
At first thanks for your work on this plugin.
I think I found a bug in this commit https://github.com/phreakadelle/maven-artifact-choicelistprovider-plugin/commit/1b0469bbd663e080e68428473c0cb1f0b1713d68
Please take a look to my comment in this commit.

Thanks in advance
Reamer

**Comment by phreakadelle** [comment]
So you are saying after the classifier there must be a "-"?

**Comment by Reamer** [comment]
We need a "-" before the classifier.

**Comment by phreakadelle** [comment]
Fixed it.
